version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "fshnkarimi/streamlit-app"
    IMAGE_TAG: "latest"
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-credentials:username
    DOCKERHUB_PASSWORD: dockerhub-credentials:password

phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
