version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "fshnkarimi/streamlit-app"
    IMAGE_TAG: "latest"
    KUBECONFIG: "/root/.kube/config"
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub-credentials:username
    DOCKERHUB_PASSWORD: dockerhub-credentials:password

phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - echo Installing kubectl...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo Installing eksctl...
      - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name my-cluster
      - echo Updating the Docker image in the Kubernetes deployment...
      - kubectl set image deployment/streamlit-app-deployment streamlit-app=$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Applying the changes to the EKS cluster...
      - kubectl apply -f streamlit-app-deployment.yaml
